---
pull_request_rules:
  - name: Automatic approval for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "check-success=build-test-lint"
    actions:
      review:
        type: APPROVE
        message: ✅ Auto-approved passing Dependabot PR with [Mergify.io](https://doc.mergify.io/actions.html#review)

  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "#approved-reviews-by>=1"
      - "check-success~=build-test-lint (2.4.x)"
      - "check-success~=build-test-lint (2.5.x)"
      - "check-success~=build-test-lint (2.6.x)"
      - "check-success~=build-test-lint (2.7.x)"
    actions:
      merge:
        method: squash
