---
pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "check-success=build-test-lint"
    actions:
      merge:
        method: squash
